### ISSUE TITLE
IE8 support

### ISSUE THREAD

**Issue by SimenB** [erikras/react-lazy-cache#2]
Tracking issue, ref erikras/redux-form#517.

Would you like to have 2 versions (one for IE8 and one for the the superior getter syntax) or just one compatible version?

I'll try to find the time to give it a crack this weekend.

**Comment by erikras** [comment]
Hmm... Since `redux-form` is only calling the getter in one place, I don't mind changing `redux-form` to use whatever method you devise that is safe for IE8, e.g. `this.cache.get('ReduxForm')`. However, I would like to maintain the current awesomer version of this library.

I guess I vote for exposing some alternate version. And then people that want to have IE8 support instead of getters can do:

``` js
import lazyCache from 'react-lazy-cache/ie8sux';
```

`redux-form` has an endpoint like this for React Native, so you can see how to do it there.

**Comment by SimenB** [comment]
PR filed: #3
